# Obtén y conoce tus datos



### 1. Importa las librerías necesarias

In [1]:
import numpy as np
import pandas as pd

### 2. Importa el dataset de este [enlace](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user) y guárdalo en una variable llamada users. Usa pd.read_csv()

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user" # creo una variable url e incluyo la dirección web
users = pd.read_csv(url, sep='|') # importo el archivo desde la dirección web con el separador |
users # muestro el dataset

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [3]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [4]:
users.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### 3. Muestra las 25 primeros registros

In [5]:
users.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### 5. Muestra los últimos 25 registros

In [6]:
users.tail(25) # uso un nuevo método, que muestra registros desde el final del dataset

     user_id  age gender     occupation zip_code
918      919   25      M          other    14216
919      920   30      F         artist    90008
920      921   20      F        student    98801
921      922   29      F  administrator    21114
922      923   21      M        student    E2E3R
923      924   29      M          other    11753
924      925   18      F       salesman    49036
925      926   49      M  entertainment    01701
926      927   23      M     programmer    55428
927      928   21      M        student    55408
928      929   44      M      scientist    53711
929      930   28      F      scientist    07310
930      931   60      M       educator    33556
931      932   58      M       educator    06437
932      933   28      M        student    48105
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

In [ ]:
users.iloc[-25:] # Otra manera de obtener los 25 últimos registros (de la posición -25 al final)

     user_id  age gender     occupation zip_code
918      919   25      M          other    14216
919      920   30      F         artist    90008
920      921   20      F        student    98801
921      922   29      F  administrator    21114
922      923   21      M        student    E2E3R
923      924   29      M          other    11753
924      925   18      F       salesman    49036
925      926   49      M  entertainment    01701
926      927   23      M     programmer    55428
927      928   21      M        student    55408
928      929   44      M      scientist    53711
929      930   28      F      scientist    07310
930      931   60      M       educator    33556
931      932   58      M       educator    06437
932      933   28      M        student    48105
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### 6. Cuántos registros hay en total en este dataset?
Resuélvelo de al menos dos formas diferentes

In [11]:
print("Para comprobar el número de registros puedo mirar la info del dataset con el método .info() y ver el valor en RangeIndex.")
print()
users.info()

Para comprobar el número de registros puedo mirar la info del dataset con el método .info() y ver el valor en RangeIndex.

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [12]:
print("También puedo comprobarlo con el método len, para comprobar su longitud.")
print()
print(f"El número de registros es de: {len(users)} registros.")

También puedo comprobarlo con el método len, para comprobar su longitud.

El número de registros es de: 943 registros.

In [ ]:
users.shape[0] # Utilizo el atributo shape, pero solo elijo el primer valor, el de las filas

943

### 7. Cuántas columnas hay en total en este dataset?
Resuélvelo de al menos dos formas diferentes

In [17]:
print("Para comprobar el número de columnas puedo mirar de nuevo la info del dataset con .info() y ver el valor en Data Columns.")
print()
users.info()

Para comprobar el número de columnas puedo mirar de nuevo la info del dataset con .info() y ver el valor en Data Columns.

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [16]:
print("También puedo comprobarlo con el método len, para comprobar su longitud.")
print()
print(f"El número de columnas es: {len(users.columns)}.")

También puedo comprobarlo con el método len, para comprobar su longitud.

El número de columnas es: 5.

In [ ]:
users.shape[1] # Utilizo el atributo shape, pero solo elijo el segundo valor, el de las columnas

5

### 8. Haz un print de cada uno de los nombres de las columnas

In [20]:
print("Los nombres de las columnas son:")
print()
for i in users.columns: #itero en cada elemento de las columnas
    print(i) # imprimo cada uno de los elementos

Los nombres de las columnas son:

user_id
age
gender
occupation
zip_code

In [22]:
print(*users.columns)

user_id age gender occupation zip_code

### 9. Accede al índice, a los nombres de las columnas y a los valores por separado

In [25]:
print(f"Así accedo al índice: {users.index}.") 
print()
print("De esta manera se indica que los índices van desde la posición 0 a la posición 943, de uno en uno.")

Así accedo al índice: RangeIndex(start=0, stop=943, step=1).

De esta manera se indica que los índices van desde la posición 0 a la posición 943, de uno en uno.

In [26]:
print(f"Estos son los nombres de las columnas: {list(users.columns.values)}.")

Estos son los nombres de las columnas: ['user_id', 'age', 'gender', 'occupation', 'zip_code'].

In [27]:
print(f"Estos son los valores:")
print()
print(*users.values, sep="\n") # imprimo los valores en un formato más legible y en vertical

Estos son los valores:

[1 24 'M' 'technician' '85711']
[2 53 'F' 'other' '94043']
[3 23 'M' 'writer' '32067']
[4 24 'M' 'technician' '43537']
[5 33 'F' 'other' '15213']
[6 42 'M' 'executive' '98101']
[7 57 'M' 'administrator' '91344']
[8 36 'M' 'administrator' '05201']
[9 29 'M' 'student' '01002']
[10 53 'M' 'lawyer' '90703']
[11 39 'F' 'other' '30329']
[12 28 'F' 'other' '06405']
[13 47 'M' 'educator' '29206']
[14 45 'M' 'scientist' '55106']
[15 49 'F' 'educator' '97301']
[16 21 'M' 'entertainment' '10309']
[17 30 'M' 'programmer' '06355']
[18 35 'F' 'other' '37212']
[19 40 'M' 'librarian' '02138']
[20 42 'F' 'homemaker' '95660']
[21 26 'M' 'writer' '30068']
[22 25 'M' 'writer' '40206']
[23 30 'F' 'artist' '48197']
[24 21 'F' 'artist' '94533']
[25 39 'M' 'engineer' '55107']
[26 49 'M' 'engineer' '21044']
[27 40 'F' 'librarian' '30030']
[28 32 'M' 'writer' '55369']
[29 41 'M' 'programmer' '94043']
[30 7 'M' 'student' '55436']
[31 24 'M' 'artist' '10003']
[32 28 'F' 'student' '78741']
[33 23 'M' 'student' '27510']
[34 38 'F' 'administrator' '42141']
[35 20 'F' 'homemaker' '42459']
[36 19 'F' 'student' '93117']
[37 23 'M' 'student' '55105']
[38 28 'F' 'other' '54467']
[39 41 'M' 'entertainment' '01040']
[40 38 'M' 'scientist' '27514']
[41 33 'M' 'engineer' '80525']
[42 30 'M' 'administrator' '17870']
[43 29 'F' 'librarian' '20854']
[44 26 'M' 'technician' '46260']
[45 29 'M' 'programmer' '50233']
[46 27 'F' 'marketing' '46538']
[47 53 'M' 'marketing' '07102']
[48 45 'M' 'administrator' '12550']
[49 23 'F' 'student' '76111']
[50 21 'M' 'writer' '52245']
[51 28 'M' 'educator' '16509']
[52 18 'F' 'student' '55105']
[53 26 'M' 'programmer' '55414']
[54 22 'M' 'executive' '66315']
[55 37 'M' 'programmer' '01331']
[56 25 'M' 'librarian' '46260']
[57 16 'M' 'none' '84010']
[58 27 'M' 'programmer' '52246']
[59 49 'M' 'educator' '08403']
[60 50 'M' 'healthcare' '06472']
[61 36 'M' 'engineer' '30040']
[62 27 'F' 'administrator' '97214']
[63 31 'M' 'marketing' '75240']
[64 32 'M' 'educator' '43202']
[65 51 'F' 'educator' '48118']
[66 23 'M' 'student' '80521']
[67 17 'M' 'student' '60402']
[68 19 'M' 'student' '22904']
[69 24 'M' 'engineer' '55337']
[70 27 'M' 'engineer' '60067']
[71 39 'M' 'scientist' '98034']
[72 48 'F' 'administrator' '73034']
[73 24 'M' 'student' '41850']
[74 39 'M' 'scientist' 'T8H1N']
[75 24 'M' 'entertainment' '08816']
[76 20 'M' 'student' '02215']
[77 30 'M' 'technician' '29379']
[78 26 'M' 'administrator' '61801']
[79 39 'F' 'administrator' '03755']
[80 34 'F' 'administrator' '52241']
[81 21 'M' 'student' '21218']
[82 50 'M' 'programmer' '22902']
[83 40 'M' 'other' '44133']
[84 32 'M' 'executive' '55369']
[85 51 'M' 'educator' '20003']
[86 26 'M' 'administrator' '46005']
[87 47 'M' 'administrator' '89503']
[88 49 'F' 'librarian' '11701']
[89 43 'F' 'administrator' '68106']
[90 60 'M' 'educator' '78155']
[91 55 'M' 'marketing' '01913']
[92 32 'M' 'entertainment' '80525']
[93 48 'M' 'executive' '23112']
[94 26 'M' 'student' '71457']
[95 31 'M' 'administrator' '10707']
[96 25 'F' 'artist' '75206']
[97 43 'M' 'artist' '98006']
[98 49 'F' 'executive' '90291']
[99 20 'M' 'student' '63129']
[100 36 'M' 'executive' '90254']
[101 15 'M' 'student' '05146']
[102 38 'M' 'programmer' '30220']
[103 26 'M' 'student' '55108']
[104 27 'M' 'student' '55108']
[105 24 'M' 'engineer' '94043']
[106 61 'M' 'retired' '55125']
[107 39 'M' 'scientist' '60466']
[108 44 'M' 'educator' '63130']
[109 29 'M' 'other' '55423']
[110 19 'M' 'student' '77840']
[111 57 'M' 'engineer' '90630']
[112 30 'M' 'salesman' '60613']
[113 47 'M' 'executive' '95032']
[114 27 'M' 'programmer' '75013']
[115 31 'M' 'engineer' '17110']
[116 40 'M' 'healthcare' '97232']
[117 20 'M' 'student' '16125']
[118 21 'M' 'administrator' '90210']
[119 32 'M' 'programmer' '67401']
[120 47 'F' 'other' '06260']
[121 54 'M' 'librarian' '99603']
[122 32 'F' 'writer' '22206']
[123 48 'F' 'artist' '20008']
[124 34 'M' 'student' '60615']
[125 30 'M' 'lawyer' '22202']
[126 28 'F' 'lawyer' '20015']
[127 33 'M' 'none' '73439']
[128 24 'F' 'marketing' '20009']
[129 36 'F' 'marketing' '07039']
[130 20 'M' 'none' '60115']
[131 59 'F' 'administrator' '15237']
[132 24 'M' 'other' '94612']
[133 53 'M' 'engineer' '78602']
[134 31 'M' 'programmer' '80236']
[135 23 'M' 'student' '38401']
[136 51 'M' 'other' '97365']
[137 50 'M' 'educator' '84408']
[138 46 'M' 'doctor' '53211']
[139 20 'M' 'student' '08904']
[140 30 'F' 'student' '32250']
[141 49 'M' 'programmer' '36117']
[142 13 'M' 'other' '48118']
[143 42 'M' 'technician' '08832']
[144 53 'M' 'programmer' '20910']
[145 31 'M' 'entertainment' 'V3N4P']
[146 45 'M' 'artist' '83814']
[147 40 'F' 'librarian' '02143']
[148 33 'M' 'engineer' '97006']
[149 35 'F' 'marketing' '17325']
[150 20 'F' 'artist' '02139']
[151 38 'F' 'administrator' '48103']
[152 33 'F' 'educator' '68767']
[153 25 'M' 'student' '60641']
[154 25 'M' 'student' '53703']
[155 32 'F' 'other' '11217']
[156 25 'M' 'educator' '08360']
[157 57 'M' 'engineer' '70808']
[158 50 'M' 'educator' '27606']
[159 23 'F' 'student' '55346']
[160 27 'M' 'programmer' '66215']
[161 50 'M' 'lawyer' '55104']
[162 25 'M' 'artist' '15610']
[163 49 'M' 'administrator' '97212']
[164 47 'M' 'healthcare' '80123']
[165 20 'F' 'other' '53715']
[166 47 'M' 'educator' '55113']
[167 37 'M' 'other' 'L9G2B']
[168 48 'M' 'other' '80127']
[169 52 'F' 'other' '53705']
[170 53 'F' 'healthcare' '30067']
[171 48 'F' 'educator' '78750']
[172 55 'M' 'marketing' '22207']
[173 56 'M' 'other' '22306']
[174 30 'F' 'administrator' '52302']
[175 26 'F' 'scientist' '21911']
[176 28 'M' 'scientist' '07030']
[177 20 'M' 'programmer' '19104']
[178 26 'M' 'other' '49512']
[179 15 'M' 'entertainment' '20755']
[180 22 'F' 'administrator' '60202']
[181 26 'M' 'executive' '21218']
[182 36 'M' 'programmer' '33884']
[183 33 'M' 'scientist' '27708']
[184 37 'M' 'librarian' '76013']
[185 53 'F' 'librarian' '97403']
[186 39 'F' 'executive' '00000']
[187 26 'M' 'educator' '16801']
[188 42 'M' 'student' '29440']
[189 32 'M' 'artist' '95014']
[190 30 'M' 'administrator' '95938']
[191 33 'M' 'administrator' '95161']
[192 42 'M' 'educator' '90840']
[193 29 'M' 'student' '49931']
[194 38 'M' 'administrator' '02154']
[195 42 'M' 'scientist' '93555']
[196 49 'M' 'writer' '55105']
[197 55 'M' 'technician' '75094']
[198 21 'F' 'student' '55414']
[199 30 'M' 'writer' '17604']
[200 40 'M' 'programmer' '93402']
[201 27 'M' 'writer' 'E2A4H']
[202 41 'F' 'educator' '60201']
[203 25 'F' 'student' '32301']
[204 52 'F' 'librarian' '10960']
[205 47 'M' 'lawyer' '06371']
[206 14 'F' 'student' '53115']
[207 39 'M' 'marketing' '92037']
[208 43 'M' 'engineer' '01720']
[209 33 'F' 'educator' '85710']
[210 39 'M' 'engineer' '03060']
[211 66 'M' 'salesman' '32605']
[212 49 'F' 'educator' '61401']
[213 33 'M' 'executive' '55345']
[214 26 'F' 'librarian' '11231']
[215 35 'M' 'programmer' '63033']
[216 22 'M' 'engineer' '02215']
[217 22 'M' 'other' '11727']
[218 37 'M' 'administrator' '06513']
[219 32 'M' 'programmer' '43212']
[220 30 'M' 'librarian' '78205']
[221 19 'M' 'student' '20685']
[222 29 'M' 'programmer' '27502']
[223 19 'F' 'student' '47906']
[224 31 'F' 'educator' '43512']
[225 51 'F' 'administrator' '58202']
[226 28 'M' 'student' '92103']
[227 46 'M' 'executive' '60659']
[228 21 'F' 'student' '22003']
[229 29 'F' 'librarian' '22903']
[230 28 'F' 'student' '14476']
[231 48 'M' 'librarian' '01080']
[232 45 'M' 'scientist' '99709']
[233 38 'M' 'engineer' '98682']
[234 60 'M' 'retired' '94702']
[235 37 'M' 'educator' '22973']
[236 44 'F' 'writer' '53214']
[237 49 'M' 'administrator' '63146']
[238 42 'F' 'administrator' '44124']
[239 39 'M' 'artist' '95628']
[240 23 'F' 'educator' '20784']
[241 26 'F' 'student' '20001']
[242 33 'M' 'educator' '31404']
[243 33 'M' 'educator' '60201']
[244 28 'M' 'technician' '80525']
[245 22 'M' 'student' '55109']
[246 19 'M' 'student' '28734']
[247 28 'M' 'engineer' '20770']
[248 25 'M' 'student' '37235']
[249 25 'M' 'student' '84103']
[250 29 'M' 'executive' '95110']
[251 28 'M' 'doctor' '85032']
[252 42 'M' 'engineer' '07733']
[253 26 'F' 'librarian' '22903']
[254 44 'M' 'educator' '42647']
[255 23 'M' 'entertainment' '07029']
[256 35 'F' 'none' '39042']
[257 17 'M' 'student' '77005']
[258 19 'F' 'student' '77801']
[259 21 'M' 'student' '48823']
[260 40 'F' 'artist' '89801']
[261 28 'M' 'administrator' '85202']
[262 19 'F' 'student' '78264']
[263 41 'M' 'programmer' '55346']
[264 36 'F' 'writer' '90064']
[265 26 'M' 'executive' '84601']
[266 62 'F' 'administrator' '78756']
[267 23 'M' 'engineer' '83716']
[268 24 'M' 'engineer' '19422']
[269 31 'F' 'librarian' '43201']
[270 18 'F' 'student' '63119']
[271 51 'M' 'engineer' '22932']
[272 33 'M' 'scientist' '53706']
[273 50 'F' 'other' '10016']
[274 20 'F' 'student' '55414']
[275 38 'M' 'engineer' '92064']
[276 21 'M' 'student' '95064']
[277 35 'F' 'administrator' '55406']
[278 37 'F' 'librarian' '30033']
[279 33 'M' 'programmer' '85251']
[280 30 'F' 'librarian' '22903']
[281 15 'F' 'student' '06059']
[282 22 'M' 'administrator' '20057']
[283 28 'M' 'programmer' '55305']
[284 40 'M' 'executive' '92629']
[285 25 'M' 'programmer' '53713']
[286 27 'M' 'student' '15217']
[287 21 'M' 'salesman' '31211']
[288 34 'M' 'marketing' '23226']
[289 11 'M' 'none' '94619']
[290 40 'M' 'engineer' '93550']
[291 19 'M' 'student' '44106']
[292 35 'F' 'programmer' '94703']
[293 24 'M' 'writer' '60804']
[294 34 'M' 'technician' '92110']
[295 31 'M' 'educator' '50325']
[296 43 'F' 'administrator' '16803']
[297 29 'F' 'educator' '98103']
[298 44 'M' 'executive' '01581']
[299 29 'M' 'doctor' '63108']
[300 26 'F' 'programmer' '55106']
[301 24 'M' 'student' '55439']
[302 42 'M' 'educator' '77904']
[303 19 'M' 'student' '14853']
[304 22 'F' 'student' '71701']
[305 23 'M' 'programmer' '94086']
[306 45 'M' 'other' '73132']
[307 25 'M' 'student' '55454']
[308 60 'M' 'retired' '95076']
[309 40 'M' 'scientist' '70802']
[310 37 'M' 'educator' '91711']
[311 32 'M' 'technician' '73071']
[312 48 'M' 'other' '02110']
[313 41 'M' 'marketing' '60035']
[314 20 'F' 'student' '08043']
[315 31 'M' 'educator' '18301']
[316 43 'F' 'other' '77009']
[317 22 'M' 'administrator' '13210']
[318 65 'M' 'retired' '06518']
[319 38 'M' 'programmer' '22030']
[320 19 'M' 'student' '24060']
[321 49 'F' 'educator' '55413']
[322 20 'M' 'student' '50613']
[323 21 'M' 'student' '19149']
[324 21 'F' 'student' '02176']
[325 48 'M' 'technician' '02139']
[326 41 'M' 'administrator' '15235']
[327 22 'M' 'student' '11101']
[328 51 'M' 'administrator' '06779']
[329 48 'M' 'educator' '01720']
[330 35 'F' 'educator' '33884']
[331 33 'M' 'entertainment' '91344']
[332 20 'M' 'student' '40504']
[333 47 'M' 'other' 'V0R2M']
[334 32 'M' 'librarian' '30002']
[335 45 'M' 'executive' '33775']
[336 23 'M' 'salesman' '42101']
[337 37 'M' 'scientist' '10522']
[338 39 'F' 'librarian' '59717']
[339 35 'M' 'lawyer' '37901']
[340 46 'M' 'engineer' '80123']
[341 17 'F' 'student' '44405']
[342 25 'F' 'other' '98006']
[343 43 'M' 'engineer' '30093']
[344 30 'F' 'librarian' '94117']
[345 28 'F' 'librarian' '94143']
[346 34 'M' 'other' '76059']
[347 18 'M' 'student' '90210']
[348 24 'F' 'student' '45660']
[349 68 'M' 'retired' '61455']
[350 32 'M' 'student' '97301']
[351 61 'M' 'educator' '49938']
[352 37 'F' 'programmer' '55105']
[353 25 'M' 'scientist' '28480']
[354 29 'F' 'librarian' '48197']
[355 25 'M' 'student' '60135']
[356 32 'F' 'homemaker' '92688']
[357 26 'M' 'executive' '98133']
[358 40 'M' 'educator' '10022']
[359 22 'M' 'student' '61801']
[360 51 'M' 'other' '98027']
[361 22 'M' 'student' '44074']
[362 35 'F' 'homemaker' '85233']
[363 20 'M' 'student' '87501']
[364 63 'M' 'engineer' '01810']
[365 29 'M' 'lawyer' '20009']
[366 20 'F' 'student' '50670']
[367 17 'M' 'student' '37411']
[368 18 'M' 'student' '92113']
[369 24 'M' 'student' '91335']
[370 52 'M' 'writer' '08534']
[371 36 'M' 'engineer' '99206']
[372 25 'F' 'student' '66046']
[373 24 'F' 'other' '55116']
[374 36 'M' 'executive' '78746']
[375 17 'M' 'entertainment' '37777']
[376 28 'F' 'other' '10010']
[377 22 'M' 'student' '18015']
[378 35 'M' 'student' '02859']
[379 44 'M' 'programmer' '98117']
[380 32 'M' 'engineer' '55117']
[381 33 'M' 'artist' '94608']
[382 45 'M' 'engineer' '01824']
[383 42 'M' 'administrator' '75204']
[384 52 'M' 'programmer' '45218']
[385 36 'M' 'writer' '10003']
[386 36 'M' 'salesman' '43221']
[387 33 'M' 'entertainment' '37412']
[388 31 'M' 'other' '36106']
[389 44 'F' 'writer' '83702']
[390 42 'F' 'writer' '85016']
[391 23 'M' 'student' '84604']
[392 52 'M' 'writer' '59801']
[393 19 'M' 'student' '83686']
[394 25 'M' 'administrator' '96819']
[395 43 'M' 'other' '44092']
[396 57 'M' 'engineer' '94551']
[397 17 'M' 'student' '27514']
[398 40 'M' 'other' '60008']
[399 25 'M' 'other' '92374']
[400 33 'F' 'administrator' '78213']
[401 46 'F' 'healthcare' '84107']
[402 30 'M' 'engineer' '95129']
[403 37 'M' 'other' '06811']
[404 29 'F' 'programmer' '55108']
[405 22 'F' 'healthcare' '10019']
[406 52 'M' 'educator' '93109']
[407 29 'M' 'engineer' '03261']
[408 23 'M' 'student' '61755']
[409 48 'M' 'administrator' '98225']
[410 30 'F' 'artist' '94025']
[411 34 'M' 'educator' '44691']
[412 25 'M' 'educator' '15222']
[413 55 'M' 'educator' '78212']
[414 24 'M' 'programmer' '38115']
[415 39 'M' 'educator' '85711']
[416 20 'F' 'student' '92626']
[417 27 'F' 'other' '48103']
[418 55 'F' 'none' '21206']
[419 37 'M' 'lawyer' '43215']
[420 53 'M' 'educator' '02140']
[421 38 'F' 'programmer' '55105']
[422 26 'M' 'entertainment' '94533']
[423 64 'M' 'other' '91606']
[424 36 'F' 'marketing' '55422']
[425 19 'M' 'student' '58644']
[426 55 'M' 'educator' '01602']
[427 51 'M' 'doctor' '85258']
[428 28 'M' 'student' '55414']
[429 27 'M' 'student' '29205']
[430 38 'M' 'scientist' '98199']
[431 24 'M' 'marketing' '92629']
[432 22 'M' 'entertainment' '50311']
[433 27 'M' 'artist' '11211']
[434 16 'F' 'student' '49705']
[435 24 'M' 'engineer' '60007']
[436 30 'F' 'administrator' '17345']
[437 27 'F' 'other' '20009']
[438 51 'F' 'administrator' '43204']
[439 23 'F' 'administrator' '20817']
[440 30 'M' 'other' '48076']
[441 50 'M' 'technician' '55013']
[442 22 'M' 'student' '85282']
[443 35 'M' 'salesman' '33308']
[444 51 'F' 'lawyer' '53202']
[445 21 'M' 'writer' '92653']
[446 57 'M' 'educator' '60201']
[447 30 'M' 'administrator' '55113']
[448 23 'M' 'entertainment' '10021']
[449 23 'M' 'librarian' '55021']
[450 35 'F' 'educator' '11758']
[451 16 'M' 'student' '48446']
[452 35 'M' 'administrator' '28018']
[453 18 'M' 'student' '06333']
[454 57 'M' 'other' '97330']
[455 48 'M' 'administrator' '83709']
[456 24 'M' 'technician' '31820']
[457 33 'F' 'salesman' '30011']
[458 47 'M' 'technician' 'Y1A6B']
[459 22 'M' 'student' '29201']
[460 44 'F' 'other' '60630']
[461 15 'M' 'student' '98102']
[462 19 'F' 'student' '02918']
[463 48 'F' 'healthcare' '75218']
[464 60 'M' 'writer' '94583']
[465 32 'M' 'other' '05001']
[466 22 'M' 'student' '90804']
[467 29 'M' 'engineer' '91201']
[468 28 'M' 'engineer' '02341']
[469 60 'M' 'educator' '78628']
[470 24 'M' 'programmer' '10021']
[471 10 'M' 'student' '77459']
[472 24 'M' 'student' '87544']
[473 29 'M' 'student' '94708']
[474 51 'M' 'executive' '93711']
[475 30 'M' 'programmer' '75230']
[476 28 'M' 'student' '60440']
[477 23 'F' 'student' '02125']
[478 29 'M' 'other' '10019']
[479 30 'M' 'educator' '55409']
[480 57 'M' 'retired' '98257']
[481 73 'M' 'retired' '37771']
[482 18 'F' 'student' '40256']
[483 29 'M' 'scientist' '43212']
[484 27 'M' 'student' '21208']
[485 44 'F' 'educator' '95821']
[486 39 'M' 'educator' '93101']
[487 22 'M' 'engineer' '92121']
[488 48 'M' 'technician' '21012']
[489 55 'M' 'other' '45218']
[490 29 'F' 'artist' 'V5A2B']
[491 43 'F' 'writer' '53711']
[492 57 'M' 'educator' '94618']
[493 22 'M' 'engineer' '60090']
[494 38 'F' 'administrator' '49428']
[495 29 'M' 'engineer' '03052']
[496 21 'F' 'student' '55414']
[497 20 'M' 'student' '50112']
[498 26 'M' 'writer' '55408']
[499 42 'M' 'programmer' '75006']
[500 28 'M' 'administrator' '94305']
[501 22 'M' 'student' '10025']
[502 22 'M' 'student' '23092']
[503 50 'F' 'writer' '27514']
[504 40 'F' 'writer' '92115']
[505 27 'F' 'other' '20657']
[506 46 'M' 'programmer' '03869']
[507 18 'F' 'writer' '28450']
[508 27 'M' 'marketing' '19382']
[509 23 'M' 'administrator' '10011']
[510 34 'M' 'other' '98038']
[511 22 'M' 'student' '21250']
[512 29 'M' 'other' '20090']
[513 43 'M' 'administrator' '26241']
[514 27 'M' 'programmer' '20707']
[515 53 'M' 'marketing' '49508']
[516 53 'F' 'librarian' '10021']
[517 24 'M' 'student' '55454']
[518 49 'F' 'writer' '99709']
[519 22 'M' 'other' '55320']
[520 62 'M' 'healthcare' '12603']
[521 19 'M' 'student' '02146']
[522 36 'M' 'engineer' '55443']
[523 50 'F' 'administrator' '04102']
[524 56 'M' 'educator' '02159']
[525 27 'F' 'administrator' '19711']
[526 30 'M' 'marketing' '97124']
[527 33 'M' 'librarian' '12180']
[528 18 'M' 'student' '55104']
[529 47 'F' 'administrator' '44224']
[530 29 'M' 'engineer' '94040']
[531 30 'F' 'salesman' '97408']
[532 20 'M' 'student' '92705']
[533 43 'M' 'librarian' '02324']
[534 20 'M' 'student' '05464']
[535 45 'F' 'educator' '80302']
[536 38 'M' 'engineer' '30078']
[537 36 'M' 'engineer' '22902']
[538 31 'M' 'scientist' '21010']
[539 53 'F' 'administrator' '80303']
[540 28 'M' 'engineer' '91201']
[541 19 'F' 'student' '84302']
[542 21 'M' 'student' '60515']
[543 33 'M' 'scientist' '95123']
[544 44 'F' 'other' '29464']
[545 27 'M' 'technician' '08052']
[546 36 'M' 'executive' '22911']
[547 50 'M' 'educator' '14534']
[548 51 'M' 'writer' '95468']
[549 42 'M' 'scientist' '45680']
[550 16 'F' 'student' '95453']
[551 25 'M' 'programmer' '55414']
[552 45 'M' 'other' '68147']
[553 58 'M' 'educator' '62901']
[554 32 'M' 'scientist' '62901']
[555 29 'F' 'educator' '23227']
[556 35 'F' 'educator' '30606']
[557 30 'F' 'writer' '11217']
[558 56 'F' 'writer' '63132']
[559 69 'M' 'executive' '10022']
[560 32 'M' 'student' '10003']
[561 23 'M' 'engineer' '60005']
[562 54 'F' 'administrator' '20879']
[563 39 'F' 'librarian' '32707']
[564 65 'M' 'retired' '94591']
[565 40 'M' 'student' '55422']
[566 20 'M' 'student' '14627']
[567 24 'M' 'entertainment' '10003']
[568 39 'M' 'educator' '01915']
[569 34 'M' 'educator' '91903']
[570 26 'M' 'educator' '14627']
[571 34 'M' 'artist' '01945']
[572 51 'M' 'educator' '20003']
[573 68 'M' 'retired' '48911']
[574 56 'M' 'educator' '53188']
[575 33 'M' 'marketing' '46032']
[576 48 'M' 'executive' '98281']
[577 36 'F' 'student' '77845']
[578 31 'M' 'administrator' 'M7A1A']
[579 32 'M' 'educator' '48103']
[580 16 'M' 'student' '17961']
[581 37 'M' 'other' '94131']
[582 17 'M' 'student' '93003']
[583 44 'M' 'engineer' '29631']
[584 25 'M' 'student' '27511']
[585 69 'M' 'librarian' '98501']
[586 20 'M' 'student' '79508']
[587 26 'M' 'other' '14216']
[588 18 'F' 'student' '93063']
[589 21 'M' 'lawyer' '90034']
[590 50 'M' 'educator' '82435']
[591 57 'F' 'librarian' '92093']
[592 18 'M' 'student' '97520']
[593 31 'F' 'educator' '68767']
[594 46 'M' 'educator' 'M4J2K']
[595 25 'M' 'programmer' '31909']
[596 20 'M' 'artist' '77073']
[597 23 'M' 'other' '84116']
[598 40 'F' 'marketing' '43085']
[599 22 'F' 'student' 'R3T5K']
[600 34 'M' 'programmer' '02320']
[601 19 'F' 'artist' '99687']
[602 47 'F' 'other' '34656']
[603 21 'M' 'programmer' '47905']
[604 39 'M' 'educator' '11787']
[605 33 'M' 'engineer' '33716']
[606 28 'M' 'programmer' '63044']
[607 49 'F' 'healthcare' '02154']
[608 22 'M' 'other' '10003']
[609 13 'F' 'student' '55106']
[610 22 'M' 'student' '21227']
[611 46 'M' 'librarian' '77008']
[612 36 'M' 'educator' '79070']
[613 37 'F' 'marketing' '29678']
[614 54 'M' 'educator' '80227']
[615 38 'M' 'educator' '27705']
[616 55 'M' 'scientist' '50613']
[617 27 'F' 'writer' '11201']
[618 15 'F' 'student' '44212']
[619 17 'M' 'student' '44134']
[620 18 'F' 'writer' '81648']
[621 17 'M' 'student' '60402']
[622 25 'M' 'programmer' '14850']
[623 50 'F' 'educator' '60187']

### 10. Cuál es el tipo de cada columna del dataset?
Hazlo de dos formas diferentes

In [23]:
print("Para comprobar el tipo de cada columna puedo mirar de nuevo la info del dataset con .info() y ver el valor en Dtype")
print()
users.info()

Para comprobar el tipo de cada columna puedo mirar de nuevo la info del dataset con .info() y ver el valor en Dtype

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [ ]:
print(f"Así accedo al tipo de cada columna:")
print()
print(users.dtypes) # utilizo el atributo dtypes para comprobar el tipo

# Nos está devolviendo una serie de Pandas

Así accedo al tipo de cada columna:

user_id       int64
age           int64
gender          str
occupation      str
zip_code        str
dtype: object

### 11. Haz un print solo de la columna de occupation
Hazlo de dos formas diferentes

In [29]:
print("Esta es la información recogida en la columna \"occupation\":")
print()
print(users.occupation) # accedo a la columna "occupation"

Esta es la información recogida en la columna "occupation":

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

In [28]:
print("Esta es otra manera de obtener la información recogida en la columna \"occupation\":")
print()
print(users["occupation"])

Esta es otra manera de obtener la información recogida en la columna "occupation":

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

### 12. ¿Cuántas profesiones diferentes hay? ¿Y personas por profesión?

In [30]:
'''
Uso el método nunique() para obtener cuántos valores únicos hay en la columna "occupation"
'''
print(f"El número de profesiones diferentes es de: {users["occupation"].nunique()}.")

El número de profesiones diferentes es de: 21.

In [38]:
sinduplicados = users["occupation"].drop_duplicates() # Con el drop elimino los valores duplicados.
print(sinduplicados)
print()
len(sinduplicados)  # Luego es solo ver la longitud restante

0         technician
1              other
2             writer
5          executive
6      administrator
8            student
9             lawyer
12          educator
13         scientist
15     entertainment
16        programmer
18         librarian
19         homemaker
22            artist
24          engineer
45         marketing
56              none
59        healthcare
105          retired
111         salesman
137           doctor
Name: occupation, dtype: str

21

In [31]:
'''
Uso el método unique() para obtener una lista de los elementos únicos en la columna "occupation"
'''
print("Y las profesiones diferentes son:")
print()
print(*users["occupation"].unique())

Y las profesiones diferentes son:

technician other writer executive administrator student lawyer educator scientist entertainment programmer librarian homemaker artist engineer marketing none healthcare retired salesman doctor

In [ ]:
'''
Utilizo el método value_counts() para obtener una serie con las ocupaciones y las veces que aparecen en la columna "occupation"
'''
print("Estas son las personas en cada profesión:")
print()
print(users["occupation"].value_counts())

Estas son las personas en cada profesión:

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [ ]:
print(users["occupation"].value_counts(ascending=True)) # Cambio el valor de asc, se obtienen los valores de menor a mayor

occupation
homemaker          7
doctor             7
none               9
lawyer            12
salesman          12
retired           14
healthcare        16
entertainment     18
marketing         26
technician        27
artist            28
scientist         31
executive         32
writer            45
librarian         51
programmer        66
engineer          67
administrator     79
educator          95
other            105
student          196
Name: count, dtype: int64

### 13. ¿Cuál es la profesión más común?

In [ ]:
'''
Uso el método idxmax() para obtener la profesión que más veces está repetida en la columna "occupation"
'''
print(f"La profesión más común es: {users['occupation'].value_counts().idxmax()}")
print()
'''
Si quiero comprobar el número de registros con el valor "student", primero creo el conteo de los registros
en una variable llamada conteo y luego entre esos registros busco los que son "student". Así obtengo el número 
de registros que son estudiantes.
'''
conteo = users['occupation'].value_counts()
numero_estudiantes = conteo['student']
print(f"El número de estudiantes en el dataset es de {numero_estudiantes}.")

La profesión más común es: student

El número de estudiantes en el dataset es de 196.

In [40]:
users['occupation'].value_counts().index[0] # cuento los valores y me quedo con el primero

'student'

### 14. Obtén un resumen de las principales medidas estadísticas de las variables numéricas.  Usa describe()

In [ ]:
print("Estas son las principales medidas estadísticas de las variables numéricas:")
print()
users.describe(include=("number")) # utilizo el include para obtener solo las medidas de variables numéricas

Estas son las principales medidas estadísticas de las variables numéricas:

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### 15. Obtén un resumen de las principales medidas estadísticas de todas las variables.  Usa describe()

In [ ]:
print("Estas son las principales medidas estadísticas de todas las variables:")
print()
users.describe(include='all') # Añado include='all', ya que de lo contrario solamente me saldrian las variables numéricas

Estas son las principales medidas estadísticas de todas las variables:

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

In [120]:
print("Estas son las principales medidas estadísticas, POR DEFECTO, de todas las variables:")
print()
users.describe() # Si no especificio que quiero que se incluyan todas las variables, me saldría lo de abajo

Estas son las principales medidas estadísticas, POR DEFECTO, de todas las variables:

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### 16. Obtén un resumen de las principales medidas estadísticas de solo la columna occupation.  Usa describe()

In [113]:
print("Estas son las principales medidas estadísticas de la columna \"occupation\":")
print()
users["occupation"].describe() # Uso el método describe(), pero solo de la columna "occupation"

Estas son las principales medidas estadísticas de la columna "occupation":

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [ ]:
users["occupation"].describe().iloc[0] # de esta manera se obtiene solo el primer valor del resumen de medidas

np.int64(943)

### 17. ¿Cuál es la edad media?

In [ ]:
'''
Utilizo el método mean() para calcular la media en la columna edad. Yo lo redondeo para que quede más exacto.
'''
print(f"La edad media, redondeada, del dataset es de {round(users['age'].mean())} años.")

La edad media, redondeada, del dataset es de 34 años.

In [42]:
users.describe().loc["mean", "age"] # una vez tengo las medidas, dame, con loc, la fila mean y la columna age

np.float64(34.05196182396607)

### 18. ¿Cuál es la edad menos frecuente?

In [ ]:
'''
Aquí lo que estoy haciendo es utilizar el método value_counts() para obtener la frecuencia de cada valor único
en la columna "age". Después uso el método idxmin() para obtener el valor menos frecuente, es decir, el valor que menos aparece.

Sin embargo, aquí me encontraré con un problema que desarrollo debajo de esta celda.
'''
print(f"La edad menos frecuente es de: {users['age'].value_counts().idxmin()} años.")

La edad menos frecuente es de: 7 años.

En este caso, a través de **idxmin()** obtengo una solución única y dado que el dataset tiene casi 1000 entradas, parece raro que solamente una edad sea la menos frecuente. Por ello, aquí debajo comprobaré las edades y sus frecuencias. En caso de que haya más de un resultado con frecuencia igual a 1, **vuelto a realizar el ejercicio** para obtener no la edad menos frecuente, sino las **edades menos frecuentes**.

In [ ]:
'''
Obtengo el conteo de los valores menos frecuentes, ya que hay más de uno, como se puede ver aquí debajo. Según el método
value_counts(), las edades 7, 66, 11, 10 y 73 solo aparecen una vez en la columna "age".
'''
conteo = users["age"].value_counts()
print("Dado que hay más de una edad menos frecuente, primero obtengo el conteo de edades y frecuencias, que es:")
print()
conteo
print(conteo)

Dado que hay más de una edad menos frecuente, primero obtengo el conteo de edades y frecuencias, que es:

age
30    39
25    38
22    37
28    36
27    35
      ..
7      1
66     1
11     1
10     1
73     1
Name: count, Length: 61, dtype: int64

In [ ]:
'''
Creo una variable que incluya una máscara. Dentro de conteo, me quedo con las edades menos frecuentes, esto lo hago 
a través de conteo == conteo.min(). Y en la misma variable, con el atributo index, obtengo los índices de esas frecuencias,
que, en realidad, son las edades que estoy buscando.

Para que quede más bonito lo imprimo en forma de lista.

Por último, compruebo que las edades menos frecuentes son las mismas que los índices cuyos valores son iguales a 1.
Y esto lo hago también a través de una máscara: conteo == 1].index).
'''
edades_menos_frecuentes = conteo[conteo == conteo.min()].index
print()
print(f"Y el conjunto de edades menos frecuentes es: {list(edades_menos_frecuentes)}")
print()
print(f"Para comprobarlo, solo tengo que buscar aquellas edades que tienen un conteo igual a 1.")
print(f"Estas son: {list(conteo[conteo == 1].index)}. Y coincide con el resultado anterior.")

Y el conjunto de edades menos frecuentes es: [7, 66, 11, 10, 73]

Para comprobarlo, solo tengo que buscar aquellas edades que tienen un conteo igual a 1.
Estas son: [7, 66, 11, 10, 73]. Y coincide con el resultado anterior.