# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [51]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [52]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")

Ya tengo cargado el csv, con separador de tabulación, y ahora, antes de nada, lo primero que hago es ver:

1.- **Información** con info()

2.- **Estadísticas** con describe ()

3.- Los **primeros registros** para entender el dataframe. De esta manera, veo que la _columna order_id_ incluye el número de pedido, la columna _quantity_ incluye la cantidad de cada producto, la columna	_item_name_ incluye el nombre de los productos, la columna _choice_description_ incluye una lista con los ingredientes y la columna _item_price_ indica el precio unitario de cada producto.

In [53]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [54]:
chipo.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [55]:
chipo.head(20)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75

### Step 3. Name of the max valued product

In [56]:
'''
Entiendo que me está pidiendo devolver el producto con el precio más alto. Aquí el problema es que la columna item_price
no tiene int, sino strings, ya que incluye el símbolo del dólar. Lo primero que habría que hacer es quitar el símbolo para poder
realizar operaciones con los precios. 
Leyendo documentación, si utilizase replace("$", ""), buscaría en las celdas exactamente el símbolo. Y lo que quiero no es eso, 
sino entrar al string y cambiar solo ese símbolo. Para ello se utiliza .str antes del replace.
'''

chipo["item_price"] = chipo["item_price"].str.replace("$", "")
print("Primero quito el símbolo $ en todos los valores de la columna item price:")
print()
chipo["item_price"]

Primero quito el símbolo $ en todos los valores de la columna item price:

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: str

In [57]:
# Ahora convierto el formato de las celdas, de string a float

chipo["item_price"] = chipo["item_price"].astype(float)
print(f"El tipo de la columna item price ahora es: {chipo["item_price"].dtype}")

El tipo de la columna item price ahora es: float64

In [58]:
# Ahora ya puedo operar con los valores de la columna y encontrar el indice con el precio máximo

print(f"El índice del producto con el precio más alto es: {chipo["item_price"].idxmax()}.")

El índice del producto con el precio más alto es: 3598.

In [59]:
# Por último, busco el nombre del producto. Para ello uso el índice y busco en la columna item_name
# Como busco por nombre, tengo que usar loc (fila = indice, columna = item_name)

productomascaro = chipo.loc[chipo["item_price"].idxmax(), "item_name"]
print(f"El producto con el precio máximo es: {productomascaro}.")

El producto con el precio máximo es: Chips and Fresh Tomato Salsa.

### Step 4. How many products cost more than $10.00?

In [60]:
# Tengo que buscar en la columna item_price las filas donde el valor sea mayor de 10

print(f"Hay {chipo[chipo["item_price"] > 10].shape[0]} productos que valen más de 10 dólares.")

# La máscara sería chipo["item_price"] > 10. Así obtengo los valores superiores a 10.
# Después simplemente utilizo el atributo shape, que me da número de filas y columnas y extraigo las filas que han
# dado positivo con la máscara.

Hay 1130 productos que valen más de 10 dólares.

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [61]:
# No sería lo mismo, ya que en un mismo pedido puede haber varios productos de más de 10 dólares. 
# Lo lógico sería que hubiese menos pedidos (mínimo los mismos que productos)
# Para poder contar los pedidos, lo que se busca es ver los valores únicos de la fila order_id con la máscara anterior.

prodmas10 = chipo[chipo["item_price"] > 10] # creo una variable para la máscara de productos de más de 10 dólares

print(f"Se han realizado {prodmas10["order_id"].nunique()} pedidos con productos de más de 10 dólares.")

# A través del método nunique() cuento los valores únicos en la columna order_id

Se han realizado 863 pedidos con productos de más de 10 dólares.

### Step 4.2: Y cuántos pedidos se han hecho de más de 20$? Es lo mismo?

In [62]:
# Habría que crear una nueva máscara para obtener los valores en item_price de más de 20
# Después, con unique(), obtener los valores únicos en la columna order_id

prodmas20 = chipo[chipo["item_price"] > 20]
print(f"Se han realizado {prodmas20["order_id"].nunique()} pedidos con productos de más de 20 dólares.")

Se han realizado 41 pedidos con productos de más de 20 dólares.

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [63]:
'''
Aquí habría que usar una máscara similar a la de los pasos 4 y 4.1, pero tenemos que irnos a la columna de quantity.
Además, antes hablábamos de precio unitario. Ahora queremos saber si en un pedido se pago más de 10 por un producto, es decir,
si la multiplicación de la columna quantity y la columna item_price es mayor a 10.
Por tanto hay que crear una nueva columna llamada total_price, que sera item_price * quantity
'''

chipo["total_item_price"] = chipo["item_price"] * chipo["quantity"]
print("Obtenemos el dataframe con la nueva columna \"total_item_price\":")
print()
chipo.head(10)

Obtenemos el dataframe con la nueva columna "total_item_price":

,order_id,quantity,item_name,choice_description,item_price,total_item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

In [64]:
pedidos10 = chipo[chipo["total_item_price"] > 10]["order_id"].nunique()
pedidos10
print(f"En {pedidos10} pedidos se han pagado más de 10 dólares por un mismo producto")

En 889 pedidos se han pagado más de 10 dólares por un mismo producto

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [65]:
'''
Aquí entiendo que tengo que crear un nuevo dataframe a partir del anterior. Solo tiene que tener la columna de item_name y de unit_price.
Esa última columna no es nueva, sino simplemente la anterior item_price renombrada. Además, quiero que me muestre precio de cada producto, sin duplicados.
Habría que tener en cuenta que un mismo producto puede tener diferentes ingredientes. Con lo que habría que buscar duplicados y descartar los que
tengan el mismo precio, dejando los que tengan precios distintos. Por ejemplo, el Chicken Bowl puede costar 16,98 o 10,98 dependiendo de sus ingredientes.
'''

df_precios_unicos = chipo[["item_name", "item_price"]] # primero selecciono las columnas que quiero visualizar
df_precios_unicos

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [66]:
df_precios_unicos = df_precios_unicos.rename(columns={"item_price":"unit_price"}) # renombro por columna, pasando nombre anterior y nuevo
print("Así quedaría el dataframe con el nuevo nombre de columna:")
print()
df_precios_unicos

Así quedaría el dataframe con el nuevo nombre de columna:

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [67]:
df_precios_unicos = df_precios_unicos.drop_duplicates() # utilizo el método drop_duplicates para eliminar los duplicados
print("Ahora elimino los duplicados, para que me quede lo que se pedía:")
print()
df_precios_unicos

Ahora elimino los duplicados, para que me quede lo que se pedía:

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4237                    Chips and Guacamole        8.50
4354                       Steak Soft Tacos       18.50
4489                    Chips and Guacamole       17.80
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [68]:
df_precios_unicos = df_precios_unicos.sort_values("item_name") # ordeno a través de la columna item_name
print("El dataframe ordenado por el nombre del producto sería:")
print()
df_precios_unicos

El dataframe ordenado por el nombre del producto sería:

              item_name  unit_price
3389  6 Pack Soft Drink       12.98
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
3195      Barbacoa Bowl        8.69
95        Barbacoa Bowl        9.25
...                 ...         ...
186   Veggie Salad Bowl       11.25
3889  Veggie Soft Tacos       16.98
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75
1395  Veggie Soft Tacos        8.49

[209 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [69]:
df_prod_mas_caro = chipo.sort_values("item_price", ascending=False) # primero ordeno el dataframe original por item_price en orden descendente
print("Este es el dataframe original ordenado de manera descendente por precio unitario:")
print()
df_prod_mas_caro

Este es el dataframe original ordenado de manera descendente por precio unitario:

,order_id,quantity,item_name,choice_description,item_price,total_item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,663.75
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25,105.75
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00,140.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00,140.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75,101.25
...,...,...,...,...,...,...
1057,435,1,Canned Soda,[Mountain Dew],1.09,1.09
117,51,1,Canned Soda,[Diet Dr. Pepper],1.09,1.09
2562,1014,1,Canned Soda,[Coca Cola],1.09,1.09
2544,1009,1,Canned Soda,[Diet Coke],1.09,1.09
2545,1009,1,Bottled Water,NaN,1.09,1.09

In [70]:
print(f"{productomascaro} fue pedido {df_prod_mas_caro.iloc[0]['quantity']} veces.")

Chips and Fresh Tomato Salsa fue pedido 15 veces.

In [71]:
'''
Anteriormente habíamos calculado productomascaro = chipo.loc[chipo["item_price"].idxmax(), "item_name"].
Ahora habría que hacer lo mismo, pero en lugar de obtener el producto, queremos obtener la cantidad pedida
'''

cantidad_mas_caro = chipo.loc[chipo["item_price"].idxmax(), "quantity"] # En lugar de item_name, pedimos la cantidad
print(f"{productomascaro} se pidió {cantidad_mas_caro} veces.")

Chips and Fresh Tomato Salsa se pidió 15 veces.

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [77]:
mascaraveggie = chipo[chipo["item_name"] == "Veggie Salad Bowl"] # creo la máscara que filtra en la columna item_name por el nombre dado
vecesveggie = mascaraveggie.shape[0] # busco la posición 0 del método shape para obtener el número de filas en las que aparece el elemento filtrado
print(f"El item Veggie Salad Bowl se pidió {vecesveggie} veces.")

El item Veggie Salad Bowl se pidió 18 veces.

### Step 9. How many times did someone order more than one Canned Soda?

In [83]:
mascarasoda = chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)] # creo la máscara que cumpla que la columna item_name sea Canned Soda
                                                                                   # y que la cantidad sea más de 1
vecessoda = mascarasoda.shape[0] # obtengo las filas que coinciden con el filtrado realizado
print(f"Las veces que alguien ha pedido más de una Canned Soda son {vecessoda}.")

Las veces que alguien ha pedido más de una Canned Soda son 20.